### ISSUE TITLE
Cloudflare DDOS prevention triggered on MongoDB Pokeapi Requests 

### ISSUE THREAD

**Issue by NiluK** [PokeAPI/pokeapi#224]
Hi all,

So it seems like the recent Pokeapi migration has created a bug on my little Pokemon project. 
If you navigate to: http://pokerank.herokuapp.com you are presented with a simple voting application   that allows the community to rate their Pokemon. Not all Pokemon have been added to the database yet, so there is an add button for those who wish to add it. 

The add button does a simple post request to my server with the required information. The server then picks up the request and attempts to generate a connection to the PokeAPI, It uses the NodeJS wrapper Pokedex-Promise-V2.

The relevant code for the server post request is:

```
var Pokedex = require('pokedex-promise-v2')
var api = new Pokedex()

[...]

app.post('/api/pokemon', function (req, res, next) {
  api.getPokemonByName(req.body.id).then(function (pokemon) {
    var primaryType = pokemon.types[1] ? pokemon.types[1] : pokemon.types[0]
    var secondaryType = pokemon.types[1] ? pokemon.types[0] : {}
    var character = new Character({
      pkdxno: req.body.id,
      pokemon: pokemon,
      description: req.body.description,
      random: [Math.random(), 0],
      image: req.body.image,
      types: {
        primaryType: primaryType,
        secondaryType: secondaryType
      }
    })
    character.save(function (err) {
      if (err) return next(err)
      res.send({ message: pokemon.name + ' has been added successfully!' })
    })
  })
})
```

Before the migration to Cloudflare, this worked fine and the JSON data was inserted successfully. After the migration, every time mongo tries to access this url, it fails due to CloudFlares DDOS prevention.

Error message

```
Unhandled rejection StatusCodeError: 503 - <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, mzDbRHz={"lZVGoXx":+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;mzDbRHz.lZVGoXx*=!+[]+!![]+!![]+!![]+!![];mzDbRHz.lZVGoXx-=+((!+[]+!![]+!![]+[])+(+[]));mzDbRHz.lZVGoXx-=!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![];mzDbRHz.lZVGoXx-=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(mzDbRHz.lZVGoXx, 10) + t.length; '; 121'
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> pokeapi.co.</h1>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="87f256e4edcb59832eb09b0c14cbc3e1"/>
    <input type="hidden" name="pass" value="1467850908.613-7jai5vldX/"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>


          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a>
            <br>
            Ray ID: 2be72359db3f1d5c
          </div>
      </td>
    </tr>
  </table>
</body>
</html>

    at new StatusCodeError (/mnt/c/Users/nkula/workspace/poke-rank/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/mnt/c/Users/nkula/workspace/poke-rank/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/mnt/c/Users/nkula/workspace/poke-rank/node_modules/request-promise/node_modules/request/request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/mnt/c/Users/nkula/workspace/poke-rank/node_modules/request-promise/node_modules/request/request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/mnt/c/Users/nkula/workspace/poke-rank/node_modules/request-promise/node_modules/request/request.js:963:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Tested with AWS, Heroku and localhost.

Any suggestions as to possible fixes/workarounds?

Thanks
Nilu

**Comment by sargunster** [comment]
Yeah, it's breaking quite a few things right now, including Postman and CORS requests. Right now I think the current rate limiting was applied temporarily, so just wait till tomorrow :P

@phalt If rate limiting will continue to exist, we'll probably have to find a different solution (or a fix for this).

**Comment by sargunster** [comment]
@NiluK if you absolutely need to work on your project before tomorrow, you can hit the JSON files in this repo for now: https://github.com/pokesource/ditto. It's a clone of all of PokeAPI's data from last week, except images.

**Comment by phalt** [comment]
Closing as we had DDoS protection up due to heavy spamming, which is now off.

@NiluK I recommend caching data to prevent large numbers of requests to the API in the future, and to ensure your application continues to run reliably.

**Comment by NiluK** [comment]
Thanks.

**Comment by mrand01** [comment]
I'm not sure if this is the appropriate place to put this, but it seems like it might be.  I've been throttled:

`StatusCodeError: 429 - {"detail":"Request was throttled. Expected available in 2159.0 seconds."}`

Any idea why this might happen?

**Comment by mrand01** [comment]
If that's the case, then I've better look at what I'm doing.

**Comment by sargunster** [comment]
@phalt Do we really need the 1000/h limit since nginx is now enforcing a 2/sec limit when deploying using docker-compose?

**Comment by phalt** [comment]
@sargunster it may well be worth turning off the throttling, but nginx stuff isn't deployed yet. So until then I think it's reasonable to have it up.
