### ISSUE TITLE
Export error on python 3.5

### ISSUE THREAD

**Issue by TorchwoodPL** [PokeAPI/pokeapi#300]
```
bin/python manage.py shell --settings=config.local
Python 3.5.3 (default, Jan 17 2017, 14:36:19)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from data.v2.build import build_all
>>> build_all()
building pokemon_v2_language
building pokemon_v2_languagename
Traceback (most recent call last):
  File "/var/www/subdomains/django/pokeapi/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/var/www/subdomains/django/pokeapi/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/subdomains/django/pokeapi/data/v2/build.py", line 2449, in build_all
    build_languages()
  File "/var/www/subdomains/django/pokeapi/data/v2/build.py", line 136, in build_languages
    for index, info in enumerate(data):
  File "/var/www/subdomains/django/pokeapi/data/v2/build.py", line 56, in with_iter
    for value in iterable:
  File "/var/www/subdomains/django/pokeapi/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 40: ordinal not in range(128)
```

Can it be easy fiaxable?

**Comment by Naramsim** [comment]
Right now Pokeapi is made only for Python 2.x

You could dive in the code and submit a PR to make it work with Python 3.x
