### ISSUE TITLE
"IndexError: list index out of range" when running `build_all()`

### ISSUE THREAD

**Issue by shawshank718** [PokeAPI/pokeapi#473]
Following the guide to setup the API on my local machine. Ran build_all() to set up the database and ran into this error.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "~/Developer/django-projects/pokeapi/data/v2/build.py", line 1701, in build_all
    _build_abilities()
  File "/Users/sathwiksingari/Developer/django-projects/pokeapi/data/v2/build.py", line 328, in _build_abilities
    build_generic((AbilityEffectText,), "ability_prose.csv", csv_record_to_objects)
  File "/Users/sathwiksingari/Developer/django-projects/pokeapi/data/v2/build.py", line 92, in build_generic
    for obj in csv_record_to_objects(csv_record):
  File "/Users/sathwiksingari/Developer/django-projects/pokeapi/data/v2/build.py", line 325, in csv_record_to_objects
    effect=scrub_str(info[3]),
  File "/Users/sathwiksingari/Developer/django-projects/pokeapi/data/v2/build.py", line 121, in scrub_str
    sub = group[1].split(":")[1]
IndexError: list index out of range
```

**Comment by shawshank718** [comment]
Upon further inspection of the data, the file ability_prose.csv seems to have a few strings that don't conform to template mark-up that Veekun is using. The issues are in the german translations for abilities with id '166' (Flower veil) and '167' (Cheek Pouch). The data seems to have been fixed in the original source for '166' but still remains wrong for '167'. 
https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/ability_prose.csv

**Comment by magical** [comment]
(Cheek Pouch is now fixed upstream: https://github.com/veekun/pokedex/commit/049fa1437be37a2c4e67895145fc639450c65ea2)

**Comment by Naramsim** [comment]
We already know this issue. There are currently three PRs open to tackle it. Two on Veekun and one here

**Comment by sathwik-sleepfit** [comment]
Cool. I've only looked in issues and didn't find anyone mention this and so created the issue. Can be closed when resolved I guess. Thank you.
