### ISSUE TITLE
Docker build fails for app container

### ISSUE THREAD

**Issue by renecatharsis** [PokeAPI/pokeapi#479]
While using your Docker (compose) guide works without issues on Ubuntu, I couldn't get it build successfully using Docker on Win10 Pro.
The build failed when installing python dependencies as part of your custom Dockerfile.

```
Building wheel for ujson (PEP 517): started
  Building wheel for ujson (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpw5azchki
       cwd: /tmp/pip-install-ldld_0zk/ujson
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/deps
  creating build/temp.linux-x86_64-3.8/deps/double-conversion
  creating build/temp.linux-x86_64-3.8/deps/double-conversion/double-conversion
  creating build/temp.linux-x86_64-3.8/lib
  creating build/temp.linux-x86_64-3.8/python
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/usr/local/include/python3.8 -c ./deps/double-conversion/double-conversion/cached-powers.cc -o build/temp.linux-x86_64-3.8/./deps/double-conversion/double-conversion/cached-powers.o -D_GNU_SOURCE
  gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ujson
```

The issue was easily resolved by adding package g++ before running pip install.

The initial data migration also failed, outputting this error:

``` 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/settings.py", line 183, in import_from_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/drf_ujson/renderers.py", line 4, in <module>
    import ujson
ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/ujson.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/config/urls.py", line 2, in <module>
    from pokemon_v2 import urls as pokemon_v2_urls
  File "/code/pokemon_v2/urls.py", line 9, in <module>
    from rest_framework import routers
  File "/usr/local/lib/python3.7/site-packages/rest_framework/routers.py", line 28, in <module>
    from rest_framework import views
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 106, in <module>
    class APIView(View):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 109, in APIView
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES
  File "/usr/local/lib/python3.7/site-packages/rest_framework/settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/settings.py", line 172, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.7/site-packages/rest_framework/settings.py", line 172, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.7/site-packages/rest_framework/settings.py", line 187, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'drf_ujson.renderers.UJSONRenderer' for API setting 'DEFAULT_RENDERER_CLASSES'. ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/ujson.cpython-37m-x86_64-linux-gnu.so).
```
The issue was easily resolved by adding package libstdc++ globally in the Dockerfile.

Changed
```
RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps
```
to
```
RUN \
    apk add --no-cache postgresql-libs libstdc++ && \
    apk add --no-cache --virtual .build-deps gcc g++ musl-dev postgresql-dev && \
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps
```

Tried building from scratch on Ubuntu after the change, still works without any issues.
I'll happily fork and provide a simple PR if requested.

**Comment by Naramsim** [comment]
Can you submit a PR? We will review it :)

**Comment by renecatharsis** [comment]
See PR #480

**Comment by renecatharsis** [comment]
Closing since PR was merged.
