### ISSUE TITLE
Build fail on latest master with Docker

### ISSUE THREAD

**Issue by Thorbenl** [PokeAPI/pokeapi#809]
Latest master fails on `make docker-setup` with 
```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 92, in handle
    exec(sys.stdin.read())
  File "<string>", line 1, in <module>
  File "/code/data/v2/build.py", line 2270, in build_all
    _build_moves()
  File "/code/data/v2/build.py", line 791, in _build_moves
    build_generic((Move,), "moves.csv", csv_record_to_objects)
  File "/code/data/v2/build.py", line 106, in build_generic
    model_class.objects.bulk_create(batch)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 471, in bulk_create
    obj_without_pk._state.db = self.db
  File "/usr/local/lib/python3.7/site-packages/cachalot/monkey_patch.py", line 174, in inner
    original(self, exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.7/site-packages/django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "pokemon_v2_move" violates foreign key constraint "pokemon_v2_move_move_target_id_47f917eb_fk_pokemon_v"
DETAIL:  Key (move_target_id)=(0) is not present in table "pokemon_v2_movetarget".
```

**Comment by Naramsim** [comment]
yes, we are aware of it.

**Comment by Naramsim** [comment]
It'd be better for you to `git checkout 24f32a8cb443af00c`
